###

GET http://localhost:8080/branches

###

GET http://localhost:8080/branches/9?expand=true
###

POST http://localhost:8080/branches
Content-Type: application/json

{
  "name": "main branch",
  "room": {
    "id": 6
  }
}

###

PUT http://localhost:8080/branches/9
Content-Type: application/json

{
  "name": "renamed branch 1"
}
###

DELETE http://localhost:8080/branches/1

###

GET http://localhost:8080/rooms/6/branches

