###

GET http://localhost:8080/calls

###

GET http://localhost:8080/calls/11
###

POST http://localhost:8080/calls/new
Content-Type: application/json

{
  "status": "started",
  "duration": 0,
  "room": {
    "id": 6
  }
}

###

PUT http://localhost:8080/calls/1
Content-Type: application/json

{
  "status": "ended",
  "duration": 100
}
###

DELETE http://localhost:8080/calls/1

###

GET http://localhost:8080/rooms/6/calls

