###

GET http://localhost:8080/room/admin_room/members

###

POST http://localhost:8080/room/best_room/connect
Content-Type: application/json

{
  "name": "Игорь",
  "roomId": "best_room"
}

###

DELETE http://localhost:8080/room/best_room/leave
Content-Type: application/json

{
  "id": "5"
}

###