###

GET http://localhost:8080/rooms

###

GET http://localhost:8080/rooms/6
###

POST http://localhost:8080/rooms
Content-Type: application/json

{
  "name": "room31",
  "owner": {
    "id": 5
  }
}

###

POST http://localhost:8080/rooms/6/15

###

PUT http://localhost:8080/rooms/6
Content-Type: application/json

{
  "name": "awesome room"
}
###

DELETE http://localhost:8080/rooms/6

###

GET http://localhost:8080/rooms/owner=4

